# Generated by Django 3.2.9 on 2021-11-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211113_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='ccreated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='ccreated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='lab',
            name='types',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Homework', 'Homework'), ('Project', 'Project')], max_length=20),
        ),
    ]
